### ISSUE TITLE
Into sleep and not lock directly

### ISSUE THREAD

**Issue by bvduijv** [plateaukao/AutoScreenOnOff#7]
If I put my phone to 'sleep' with the on/off button and I turn it back on It only asks me to put in my pin if I wait longer than 10 minutes. Is it possible to also implement this into your app?

an example of my settings: http://cdn8.howtogeek.com/wp-content/uploads/2013/06/android-screen-lock.png

ps. I have to put in a PIN due to security Exchange policy

**Comment by jumper047** [comment]
Can you send this version for me too? I have the same problem as in issue #12.
